const claims = [
  {name:'Oda Overivrig',team:'Skadeplattform',date:'2026-08-16',note:'Fristen gikk ut mens Oda antakeligvis stolte på at historikken slettet seg selv.'},
  {name:'Peder Pult',team:'Erstatningsorkesteret',date:'2026-08-23',note:'Saken er nå dobbelt opp. Kalenderen har dessverre ingen empati.'},
  {name:'Nora Nøkkel',team:'Vilkårsvakten',date:'2026-09-04',note:'To uker igjen. Bjarne har allerede funnet frem den passive aggressive brevmalen.'},
  {name:'Tobias Tastatur',team:'Skadeanalyse',date:'2026-09-12',note:'Saken er ny. Vi later foreløpig som om dette kan løses uten inkasso.'},
  {name:'Linn Lås',team:'Kundeoppgjør',date:'2026-08-09',settled:true,note:'Oppgjør godkjent. Bakverket var forsvarlig, og tilliten er under behandling.'}
];
const label = {open:'AKTIV OBSERVASJON',warning:'TILTAKSVINDU LUKKES',collections:'NIVÅ RØD · BOLLEINKASSO',settled:'OPERASJON AVSLUTTET'};
const days = date => Math.max(0,Math.floor((Date.now()-new Date(`${date}T12:00:00`).getTime())/86400000));
const status = claim => claim.settled?'settled':days(claim.date)>28?'collections':days(claim.date)>14?'warning':'open';
const formatDate = date => new Intl.DateTimeFormat('nb-NO',{day:'numeric',month:'long',year:'numeric'}).format(new Date(`${date}T12:00:00`));
const message = text => {document.querySelector('#bowl-message').textContent=`Bjarne varsler: ${text}`;};
function render(){
  const stats=document.querySelector('#bowl-stats');stats.replaceChildren();
  for(const [count,title] of [[claims.filter(c=>!c.settled).length,'Åpne saker'],[claims.filter(c=>status(c)==='warning').length,'Frist nærmer seg'],[claims.filter(c=>status(c)==='collections').length,'Hos Bolleinkasso'],[claims.filter(c=>c.settled).length,'Oppgjør godkjent motvillig']]){const item=document.createElement('div');const strong=document.createElement('strong');strong.textContent=count;item.append(strong,title);stats.append(item);}
  const grid=document.querySelector('#bowl-claims');grid.replaceChildren();
   claims.forEach((claim,index)=>{const state=status(claim),card=document.createElement('article');card.className=`bowl-card ${state}`;const file=document.createElement('span');file.className='case-file';file.textContent=`SAK-${String(index+401).padStart(4,'0')}`;const heading=document.createElement('h3');heading.textContent=claim.name;const team=document.createElement('p');team.textContent=claim.team;const badge=document.createElement('strong');badge.textContent=label[state]+(state==='collections'?' · DOBBELT OPP':'');const deadline=document.createElement('div');deadline.className='bowl-deadline';const summary=document.createElement('strong');summary.textContent=claim.settled?'Oppgjør registrert':days(claim.date)>28?`Frist oversittet med ${days(claim.date)-28} dager`:`${28-days(claim.date)} dager til Bolleinkasso`;deadline.append(summary);if(!claim.settled){const progress=document.createElement('div');progress.className='bowl-progress';const bar=document.createElement('span');bar.style.width=`${Math.min(100,days(claim.date)/28*100)}%`;progress.append(bar);deadline.append(progress,`Bot gitt ${formatDate(claim.date)} · Bolleinkasso etter 4 uker`);}const note=document.createElement('p');note.className='bowl-note';note.textContent=claim.note;card.append(file,badge,heading,team,deadline,note);if(!claim.settled){const button=document.createElement('button');button.type='button';button.textContent='BEKREFT OPPGJØR';button.addEventListener('click',()=>{claim.settled=true;claim.note='Oppgjør registrert. Ikke fordi jeg er imponert, men fordi bakverket var forsvarlig.';message(`${claim.name} er registrert som oppgjort. Tillit er fortsatt under behandling.`);render();});card.append(button);}grid.append(card);});
}
const form=document.querySelector('#bowl-form'),toggle=document.querySelector('#bowl-toggle');toggle.addEventListener('click',()=>{form.hidden=!form.hidden;toggle.setAttribute('aria-expanded',String(!form.hidden));toggle.textContent=form.hidden?'Registrer bollesak':'Lukk registrering';});form.addEventListener('submit',event=>{event.preventDefault();const name=form.elements.name.value.trim(),team=form.elements.team.value.trim();if(!name||!team)return;claims.unshift({name,team,date:new Date().toISOString().slice(0,10),note:'Ny sak registrert. Skjermlåsen var tydeligvis på en uplanlagt pause.'});message(`Ny bollesak for ${name} er registrert. Jeg har motvillig opprettet dokumentasjonen.`);form.reset();toggle.click();render();});
render();
